set(OpenGL_GL_PREFERENCE "GLVND")

# set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIGURATION>")
# set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIGURATION>")

# add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/repo/SDL" EXCLUDE_FROM_ALL)
# add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/repo/SDL_image" EXCLUDE_FROM_ALL)

add_library(glm INTERFACE)
target_include_directories(
    glm INTERFACE
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
    $<INSTALL_INTERFACE:include>
)

find_package(Jolt REQUIRED PATHS "${CMAKE_CURRENT_SOURCE_DIR}/lib/cmake" NO_DEFAULT_PATH)

