name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          repository: IDKGameEngine/idk_build
          path: ${GITHUB_WORKSPACE}/idk_build

      - name: Checkout idk_core
        uses: actions/checkout@v4
        with:
          repository: IDKGameEngine/idk_core
          path: ${GITHUB_WORKSPACE}/idk_core
    
      - name: Checkout idk_gfx
        uses: actions/checkout@v4
        with:
          repository: IDKGameEngine/idk_gfx
          path: ${GITHUB_WORKSPACE}/idk_gfx
    
      - name: Checkout idk_engine
        uses: actions/checkout@v4
        with:
          repository: IDKGameEngine/idk_engine
          path: ${GITHUB_WORKSPACE}/idk_engine
    
      - name: Checkout idk_game
        uses: actions/checkout@v4
        with:
          repository: IDKGameEngine/idk_game
          path: ${GITHUB_WORKSPACE}/idk_game

      - name: Run a multiline script
        run: ${GITHUB_WORKSPACE}/idk_build/script/build.sh --target idk_game --debug
          # printf "\n\nAAAA\n%s" "$(ls ./)"
          # printf "\n\nBBBB\n%s" "$(ls ../)"
          # printf "\n\nCCCC\n%s" "$(ls *)"

          
#/script/build.sh --target idk_game --debug
